<a href="https://colab.research.google.com/github/ShraddhaNindekar/Java-Project/blob/main/Loc_iloc_function_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}
df=pd.DataFrame(data)
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

In [ ]:
df["Operation_Duration_Min"].idxmax()

1

In [ ]:
df['Operation_Duration_Min'].idxmin()

6

In [ ]:
df[["Patient_ID","Surgery_Type"]]

  Patient_ID      Surgery_Type
0       P101   Cholecystectomy
1       P102              CABG
2       P103      Appendectomy
3       P104     Hernia Repair
4       P105  Knee Replacement
5       P106              PTCA
6       P107      Appendectomy
7       P108   Cholecystectomy
8       P109     Hernia Repair
9       P110  Knee Replacement

In [ ]:
df.loc[df["Operation_Duration_Min"].idxmax(),["Patient_ID","Surgery_Type"]]

Patient_ID      P102
Surgery_Type    CABG
Name: 1, dtype: object

In [ ]:
print(df.loc[df["Operation_Duration_Min"].idxmin(),["Patient_ID","Surgery_Type"]])

Patient_ID              P107
Surgery_Type    Appendectomy
Name: 6, dtype: object

In [ ]:
print(df.loc[0])

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [ ]:
print(df.iloc[1])

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object